[package]
name = "bunyan"
version = "0.0.1"
authors = ["Luca Palmieri <rust@lpalmieri.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A CLI to pretty print logs in bunyan format. A Rust port of the original JavaScript bunyan CLI."

[[bin]]
path = "src/main.rs"
name = "bunyan"

[lib]
path = "src/lib.rs"
name = "bunyan"

[dependencies]
clap = "3.0.0-beta.2"
anyhow = "1.0.33"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
chrono = "0.4.19"

[dev-dependencies]
assert_cmd = "1.0.1"
predicates = "1.0.5"
